version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      # 新增這一行，指定到 Dockerfile folder 裡面的 Dockerfile
      dockerfile: Dockerfile/Dockerfile
      context: .
      args:
        - NODE_VERSION=${DOCKER_NODE_VERSION}
    ports:
      # 把本機的 port 跟 container 的 port 綁定
      - '${DOCKER_HOST_MACHINE_PORT}:3000'
    volumes:
      - .:/app